### ISSUE TITLE
Missing exports from the resource "fxl"

### ISSUE THREAD

**Issue by iTexZoz** [Cyntaax/fivem-webbed#2]
Hello, this export is not available.

```
exports.fxl:matchRoute(z._path, path)
```

Is there an external dependency not mentioned in the description? Or is it simply due to an oversight ? 😀

**Comment by Cyntaax** [comment]
Oops! Was an oversight! I'll get it fixed in a bit

**Comment by iTexZoz** [comment]
Thank u 🤟

**Comment by Kraleemil** [comment]
Hi the export `exports.fxl:parseCookie(request.headers.Cookie)` is not accessible either

**Comment by Kraleemil** [comment]
> Hi the export `exports.fxl:parseCookie(request.headers.Cookie)` is not accessible either

Made a pull request to fix it @ #5
