### ISSUE TITLE
attempt to index a nil value (global 'Router')

### ISSUE THREAD

**Issue by qubitrepos** [Cyntaax/fivem-webbed#7]
Resource is not see server.lua in fivem-webbed, error : attempt to index a nil value (global 'Router')
![image](https://github.com/Cyntaax/fivem-webbed/assets/13704525/45708eec-8390-44d8-a9ab-93737c91aec6)

api resource fxmanifest
```
fx_version 'bodacious'
game 'common'
version  '_'


server_scripts {
    '@fivem-webbed/server/server.lua',
    'server/server.lua'
}
```

api resource server.lua code 
```
local player = Router.new()

player:Get("/:playerId", function(req, res)
    local target = tonumber(req:Param("playerId"))
    print('Player name', GetPlayerName(target))
    return 200, {
        name = GetPlayerName(target),
        target = target
    }
end)

Server.use("/players", player)
Server.listen()
```

![image](https://github.com/Cyntaax/fivem-webbed/assets/13704525/45cf7065-a25f-45b0-b661-a0db31f4e03d)
fivem-webbed fxmanifest
```
fx_version 'bodacious'
game 'common'
version  '_'

server_scripts {
    'server/path.js',
    'server/*.lua'
}
```

**Comment by aethyriion** [comment]
Hello, per the instructions in the README, use the latest release https://github.com/Cyntaax/fivem-webbed/releases/tag/1.0.3

Don't just try to use the files individually

**Comment by qubitrepos** [comment]
im using latest releases 1.0.3, but not see server.lua on fivem-webbed, I did not make any changes to the file, 
I downloaded it again via releases, the resulta is the same unfortunately

**Comment by qubitrepos** [comment]
It's worked thanks, I accidentally downloaded the zip from the releases, awsome work!
